version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/cardano_scanner
      - JWT_SECRET=${JWT_SECRET}
      - BLOCKFROST_API_KEY=${BLOCKFROST_API_KEY}
      - BLOCKFROST_NETWORK=${BLOCKFROST_NETWORK}
    depends_on:
      - db
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cardano_scanner
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
