name: Deploy Scanner

- name: 🔍 Debug secrets (safe output)
    run: | 
      echo "🔑 SSH_PRIVATE_KEY (first 2 lines):"
      echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 2
      echo "..."
      echo "${{ secrets.SSH_PRIVATE_KEY }}" | tail -n 2
      echo ""
      
      echo "🌐 SSH_HOST:"
      echo "${{ secrets.SSH_HOST }}"
      echo ""
      
      echo "👤 SSH_USERNAME:"
      echo "${{ secrets.SSH_USERNAME }}"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/apps/new-scanner"

      - name: Execute deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps
            docker compose build new-scanner
            docker compose up -d new-scanner
